// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgrgxfgbxcztlcwosorc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhncmd4ZmdieGN6dGxjd29zb3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNzY1OTAsImV4cCI6MjA3MjY1MjU5MH0.XURhZtUTqQq92t1NRujyfBqR7O74Q_vKklic1n5O93U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});